apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-app-config
  namespace: default
  labels:
    app: todo-app
data:
  NODE_ENV: "production"
  PORT: "3000"
  DB_HOST: "todo-db"
  DB_PORT: "5432"
  DB_NAME: "todo_app"