services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: todo-app:latest
    container_name: todo-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=todo_app
      - DB_HOST=db
      - DB_PORT=5432
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    depends_on:
      - db
    command: npm run dev

  db:
    image: postgres:16-alpine
    container_name: todo-db
    restart: unless-stopped
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todo_app
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: