apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: default
type: Opaque
data:
  username: cG9zdGdyZXM=  # postgres encoded in base64
  password: cG9zdGdyZXM=  # postgres encoded in base64