apiVersion: v1
kind: Service
metadata:
  name: todo-db
  namespace: default
  labels:
    app: todo-db
    tier: database
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app: todo-db